name: Manual .NET Build & Test Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet-and-build:
    runs-on: windows-latest

    steps:
    - name: Greet the person
      run: echo "Hello ${{ inputs.name }} "

    - name:  Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Change this if you're using .NET 6 or 8

    - name:  Restore dependencies
      run: dotnet restore

    - name:  Build the solution
      run: dotnet build --configuration Release --no-restore

    - name:  Run unit tests
      run: dotnet test --no-build --verbosity normal
